### ISSUE TITLE
Cannot find procedure "swapShape" in AEpickableTemplate

### ISSUE THREAD

**Issue by semontesdeoca** [eddiehoyle/screenspace#11]
I've compiled it for Maya 2019 and everything seems to be running correctly, but every time I show the pickable node in the attribute editor I get the following error message: 

> // Error: line 1: Cannot find procedure "swapShape". // 

There seems to be a procedure missing within the _AEpickableTemplate.mel_ file (line 7).

I've removed the "swapShape" procedure there and everything is fine now. What was the procedure intended for?

**Comment by eddiehoyle** [comment]
Ah-ha, nice catch. Here's an older version of [AEpickableTemplate.mel](https://github.com/eddiehoyle/screenspace/blob/110e189e2717c848e1fe89f7d991a476136967a4/src/scripts/AEpickerTemplate.mel#L1-L14) that contains the procedure.

I think I originally intended to use it to rename UI labels for different shapes (eg: width/height for square, radius for circle). I must've changed my mind and removed it.

Feel free to submit a PR with the changes! Otherwise I'll get this patched up.

**Comment by semontesdeoca** [comment]
Alright, I understand. I just submitted a pull request with the small fix. Thanks!
